# Generated by Django 2.1.1 on 2018-09-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=128)),
                ('project_company', models.CharField(max_length=128)),
                ('project_description', models.CharField(max_length=512)),
            ],
        ),
    ]
